# Generated by Django 5.2.7 on 2025-10-18 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_name', models.CharField(max_length=100)),
                ('fantasy_name', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('trade_terms', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_perishable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('measurement_unit', models.CharField(choices=[('U', 'Unidades'), ('KG', 'Kilogramos'), ('L', 'Litros')], max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='Products.category')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('iva', models.DecimalField(decimal_places=2, default=1.19, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_histories', to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_perishable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('measurement_unit', models.CharField(choices=[('U', 'Unidades'), ('KG', 'Kilogramos'), ('L', 'Litros')], max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='Products.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='Products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=100, unique=True)),
                ('expiration_date', models.DateField()),
                ('min_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('raw_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.rawmaterial')),
            ],
        ),
    ]
