# Generated by Django 5.2.5 on 2025-11-20 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_pricehistories_product_and_more'),
        ('Sells', '0008_remove_loteproducto_producto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='RawMaterial',
        ),
    ]
