# Generated by Django 5.2.5 on 2025-11-05 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_batch_created_at_remove_batch_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistories',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='Products.product'),
        ),
    ]
