# Generated by Django 5.2.5 on 2025-11-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_batch_product_alter_batch_raw_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='max_quantity',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='min_quantity',
        ),
        migrations.AddField(
            model_name='batch',
            name='serie',
            field=models.BooleanField(default=False),
        ),
    ]
