# Generated by Django 5.2.5 on 2025-11-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_delete_product_delete_rawmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='is_perishable',
        ),
        migrations.AddField(
            model_name='producto',
            name='alerta_bajo_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='alerta_por_vencer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='batch_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='ean_upc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='max_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='min_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='model_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='reordering_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='serie_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='standard_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='technical_sheet',
            field=models.FileField(blank=True, null=True, upload_to='technical_sheets'),
        ),
        migrations.AddField(
            model_name='producto',
            name='uom_purchase',
            field=models.CharField(choices=[('U', 'Unidades'), ('KG', 'Kilogramos'), ('L', 'Litros')], default='U', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='uom_sale',
            field=models.CharField(choices=[('U', 'Unidades'), ('KG', 'Kilogramos'), ('L', 'Litros')], default='U', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='url_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='measurement_unit',
            field=models.CharField(choices=[('U', 'Unidades'), ('KG', 'Kilogramos'), ('L', 'Litros')], default='U', max_length=100),
        ),
    ]
