# Generated by Django 5.2.5 on 2025-11-21 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_producto_is_perishable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='measurement_unit',
        ),
    ]
