# Generated by Django 5.2.5 on 2025-11-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_batch_max_quantity_remove_batch_min_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
