# Generated by Django 5.2.5 on 2025-11-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_producto_measurement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='measurement_unit',
            field=models.CharField(choices=[('U', 'Unidades'), ('KG', 'Kilogramos'), ('L', 'Litros')], default='U', max_length=100),
        ),
    ]
