# Generated by Django 5.2.5 on 2025-11-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_producto_measurement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='is_perishable',
            field=models.BooleanField(default=False),
        ),
    ]
