# Generated by Django 5.2.5 on 2025-11-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_producto_is_perishable'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='Chile', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.CharField(choices=[('CLP', 'Peso Chileno'), ('USD', 'Dólar'), ('EUR', 'Euro')], default='CLP', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento general (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_preferred',
            field=models.BooleanField(default=False, help_text='Proveedor preferente'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='lead_time_days',
            field=models.IntegerField(default=7, help_text='Tiempo de entrega en días'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms_days',
            field=models.IntegerField(default=30, help_text='Días de plazo de pago'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='web_site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='trade_terms',
            field=models.TextField(blank=True, help_text='Términos y condiciones comerciales', null=True),
        ),
    ]
