# Generated by Django 5.2.5 on 2025-11-21 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile_per_page'),
        ('Products', '0008_supplier_address_supplier_city_supplier_country_and_more'),
        ('Sells', '0010_remove_lote_inventario_remove_serie_inventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialclass',
            name='alerta_bajo_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='alerta_por_vencer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='batch_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='ean_upc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='iva',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='max_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='min_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='model_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='reordering_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='serie_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='standard_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='technical_sheet',
            field=models.FileField(blank=True, null=True, upload_to='technical_sheets'),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='uom_purchase',
            field=models.CharField(choices=[('U', 'Unidades'), ('KG', 'Kilogramos'), ('L', 'Litros')], default='U', max_length=100),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='uom_sale',
            field=models.CharField(choices=[('U', 'Unidades'), ('KG', 'Kilogramos'), ('L', 'Litros')], default='U', max_length=100),
        ),
        migrations.AddField(
            model_name='rawmaterialclass',
            name='url_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='measurement_unit',
            field=models.CharField(choices=[('U', 'Unidades'), ('KG', 'Kilogramos'), ('L', 'Litros')], default='U', max_length=100),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='sku',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='lead_time_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='trade_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario', to='Sells.warehouse')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario', to='Products.rawmaterialclass')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario', to='Products.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('I', 'Ingreso'), ('S', 'Salida'), ('D', 'Devolucion'), ('T', 'Transferencia'), ('A', 'Ajuste')], default='I', max_length=20)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='Products.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='Products.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('I', 'Ingreso'), ('S', 'Salida'), ('D', 'Devolucion'), ('T', 'Transferencia'), ('A', 'Ajuste')], default='I', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('batch_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('serie_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='Sells.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Accounts.profile')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='Sells.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactiondetails', to='Products.lote')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactiondetails', to='Products.serie')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='Products.transaction')),
            ],
        ),
    ]
