# Generated by Django 5.2.5 on 2025-11-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_rawmaterialclass_alerta_bajo_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='batch_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='serie_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
