# Generated by Django 5.2.5 on 2025-11-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_alter_transaction_batch_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serie',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
