# Generated by Django 5.2.5 on 2025-11-23 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_alter_lote_codigo_alter_serie_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='alerta_bajo_stock',
            field=models.BooleanField(default=False, verbose_name='Alerta: bajo stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='alerta_por_vencer',
            field=models.BooleanField(default=False, verbose_name='Alerta: por vencer'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='batch_control',
            field=models.BooleanField(default=False, verbose_name='Control de lote'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='Products.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Factor de conversión'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ean_upc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='EAN/UPC'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='is_perishable',
            field=models.BooleanField(default=False, verbose_name='Perecedero'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='iva',
            field=models.IntegerField(default=0, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='max_stock',
            field=models.IntegerField(default=0, verbose_name='Stock máximo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='measurement_unit',
            field=models.CharField(choices=[('U', 'Unidades'), ('KG', 'Kilogramos'), ('L', 'Litros')], default='U', max_length=100, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='min_stock',
            field=models.IntegerField(default=0, verbose_name='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='model_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de modelo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='reordering_level',
            field=models.IntegerField(default=0, verbose_name='Nivel de reorden'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='serie_control',
            field=models.BooleanField(default=False, verbose_name='Control de serie'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='standard_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo estándar'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='technical_sheet',
            field=models.FileField(blank=True, null=True, upload_to='technical_sheets', verbose_name='Ficha técnica'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='uom_purchase',
            field=models.CharField(choices=[('U', 'Unidades'), ('KG', 'Kilogramos'), ('L', 'Litros')], default='U', max_length=100, verbose_name='Unidad de medida (compra)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='uom_sale',
            field=models.CharField(choices=[('U', 'Unidades'), ('KG', 'Kilogramos'), ('L', 'Litros')], default='U', max_length=100, verbose_name='Unidad de medida (venta)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='url_image',
            field=models.URLField(blank=True, null=True, verbose_name='URL imagen'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='alerta_bajo_stock',
            field=models.BooleanField(default=False, verbose_name='Alerta: bajo stock'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='alerta_por_vencer',
            field=models.BooleanField(default=False, verbose_name='Alerta: por vencer'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='batch_control',
            field=models.BooleanField(default=False, verbose_name='Control de lote'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='Products.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Factor de conversión'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='ean_upc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='EAN/UPC'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='is_perishable',
            field=models.BooleanField(default=False, verbose_name='Perecedero'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='iva',
            field=models.IntegerField(default=0, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='max_stock',
            field=models.IntegerField(default=0, verbose_name='Stock máximo'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='measurement_unit',
            field=models.CharField(choices=[('U', 'Unidades'), ('KG', 'Kilogramos'), ('L', 'Litros')], default='U', max_length=100, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='min_stock',
            field=models.IntegerField(default=0, verbose_name='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='model_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de modelo'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='reordering_level',
            field=models.IntegerField(default=0, verbose_name='Nivel de reorden'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='serie_control',
            field=models.BooleanField(default=False, verbose_name='Control de serie'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='standard_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo estándar'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='Products.supplier', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='technical_sheet',
            field=models.FileField(blank=True, null=True, upload_to='technical_sheets', verbose_name='Ficha técnica'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='uom_purchase',
            field=models.CharField(choices=[('U', 'Unidades'), ('KG', 'Kilogramos'), ('L', 'Litros')], default='U', max_length=100, verbose_name='Unidad de medida (compra)'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='uom_sale',
            field=models.CharField(choices=[('U', 'Unidades'), ('KG', 'Kilogramos'), ('L', 'Litros')], default='U', max_length=100, verbose_name='Unidad de medida (venta)'),
        ),
        migrations.AlterField(
            model_name='rawmaterialclass',
            name='url_image',
            field=models.URLField(blank=True, null=True, verbose_name='URL imagen'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bussiness_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='Chile', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='currency',
            field=models.CharField(choices=[('CLP', 'Peso Chileno'), ('USD', 'Dólar'), ('EUR', 'Euro')], default='CLP', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre fantasía'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_preferred',
            field=models.BooleanField(default=False, verbose_name='Preferido'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='lead_time_days',
            field=models.IntegerField(default=7, verbose_name='Días de atención'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms_days',
            field=models.IntegerField(default=30, verbose_name='Días de pago'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='rut',
            field=models.CharField(max_length=20, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='trade_terms',
            field=models.TextField(blank=True, null=True, verbose_name='Términos de comercio'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='web_site',
            field=models.URLField(blank=True, null=True, verbose_name='Página web'),
        ),
    ]
