# Generated by Django 5.2.8 on 2025-12-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='batch_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='serie_code',
        ),
        migrations.AddField(
            model_name='producto',
            name='deficit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Deficit'),
        ),
    ]
