# Generated by Django 5.2.8 on 2025-12-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_rename_batch_code_transaction_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialclass',
            name='deficit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Deficit'),
        ),
    ]
