# Generated by Django 5.2.5 on 2025-10-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='privilege_level',
        ),
    ]
