# Generated by Django 5.2.8 on 2025-12-01 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile_per_page'),
        ('Sells', '0013_warehouse_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('bussiness_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fantasy_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre fantasía')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('web_site', models.URLField(blank=True, null=True, verbose_name='Página web')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lilis_warehouses', to='Sells.warehouse')),
            ],
        ),
    ]
