# Generated by Django 5.2.8 on 2025-12-01 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_lilis'),
        ('Sells', '0013_warehouse_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lilis',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lilis_warehouses', to='Sells.warehouse'),
        ),
    ]
