# Generated by Django 5.2.8 on 2025-12-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_lilis_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lilis',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
