# Generated by Django 5.2.8 on 2025-12-01 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_lilis_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lilis',
            name='warehouse',
        ),
    ]
