# Generated by Django 5.2.5 on 2025-11-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
