# Generated by Django 5.2.5 on 2025-10-19 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_batch_created_at_remove_batch_expiration_date_and_more'),
        ('Sells', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorderdetail',
            name='batch',
        ),
        migrations.AddField(
            model_name='saleorderdetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='Products.product'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
