# Generated by Django 5.2.5 on 2025-11-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sells', '0002_transaction_batch_code_transaction_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
