# Generated by Django 5.2.5 on 2025-11-15 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_batch_max_quantity_remove_batch_min_quantity_and_more'),
        ('Sells', '0003_alter_transaction_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='Products.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='serie_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
