# Generated by Django 5.2.5 on 2025-11-18 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sells', '0003_materiaprimainventario_lotemateriaprima'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotemateriaprima',
            old_name='inventario',
            new_name='materia_prima',
        ),
        migrations.RenameField(
            model_name='materiaprimainventario',
            old_name='catalogo',
            new_name='materia_prima',
        ),
    ]
