# Generated by Django 5.2.5 on 2025-11-19 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('Sells', '0004_rename_inventario_lotemateriaprima_materia_prima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_inventario', to='Sells.warehouse')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_inventario', to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('I', 'Ingreso'), ('S', 'Salida'), ('D', 'Devolucion'), ('T', 'Transferencia'), ('A', 'Ajuste')], default='I', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='Sells.productoinventario')),
            ],
        ),
    ]
