# Generated by Django 5.2.5 on 2025-11-19 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('Sells', '0005_productoinventario_loteproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='Products.rawmaterialclass'),
        ),
    ]
