# Generated by Django 5.2.5 on 2025-11-19 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sells', '0006_alter_transaction_raw_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='raw_material',
        ),
    ]
