# Generated by Django 5.2.5 on 2025-11-20 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_pricehistories_product_and_more'),
        ('Sells', '0007_remove_transaction_batch_remove_transaction_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='materiaprimainventario',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='materiaprimainventario',
            name='materia_prima',
        ),
        migrations.RemoveField(
            model_name='productoinventario',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='productoinventario',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='client',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='saleorderdetail',
            name='sale_order',
        ),
        migrations.RemoveField(
            model_name='saleorderdetail',
            name='product',
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario', to='Sells.warehouse')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario', to='Products.rawmaterialclass')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario', to='Products.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('I', 'Ingreso'), ('S', 'Salida'), ('D', 'Devolucion'), ('T', 'Transferencia'), ('A', 'Ajuste')], default='I', max_length=20)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='Sells.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='Sells.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactiondetails', to='Sells.lote')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactiondetails', to='Sells.serie')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='Sells.transaction')),
            ],
        ),
        migrations.DeleteModel(
            name='LoteMateriaPrima',
        ),
        migrations.DeleteModel(
            name='LoteProducto',
        ),
        migrations.DeleteModel(
            name='MateriaPrimaInventario',
        ),
        migrations.DeleteModel(
            name='ProductoInventario',
        ),
        migrations.DeleteModel(
            name='SaleOrder',
        ),
        migrations.DeleteModel(
            name='SaleOrderDetail',
        ),
    ]
