# Generated by Django 5.2.5 on 2025-11-20 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sells', '0008_remove_loteproducto_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactiondetails', to='Sells.lote'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactiondetails', to='Sells.serie'),
        ),
    ]
