# Generated by Django 5.2.5 on 2025-11-21 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sells', '0009_alter_transactiondetail_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='client',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionDetail',
        ),
    ]
