# Generated by Django 5.2.5 on 2025-11-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sells', '0010_remove_lote_inventario_remove_serie_inventario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='client',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='client',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_suspended',
        ),
        migrations.RemoveField(
            model_name='client',
            name='max_debt',
        ),
        migrations.RemoveField(
            model_name='wareclient',
            name='status',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(default='Chile', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.CharField(choices=[('CLP', 'Peso Chileno'), ('USD', 'Dólar'), ('EUR', 'Euro')], default='CLP', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='client',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_preferred',
            field=models.BooleanField(default=False, verbose_name='Preferido'),
        ),
        migrations.AddField(
            model_name='client',
            name='lead_time_days',
            field=models.IntegerField(default=7, verbose_name='Días de atención'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_terms_days',
            field=models.IntegerField(default=30, verbose_name='Días de pago'),
        ),
        migrations.AddField(
            model_name='client',
            name='trade_terms',
            field=models.TextField(blank=True, null=True, verbose_name='Términos de comercio'),
        ),
        migrations.AddField(
            model_name='client',
            name='web_site',
            field=models.URLField(blank=True, null=True, verbose_name='Página web'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bussiness_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre fantasía'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rut',
            field=models.CharField(max_length=20, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Área total'),
        ),
    ]
