# Generated by Django 5.2.5 on 2025-11-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sells', '0011_delete_location_remove_client_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wareclient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
