# Generated by Django 5.2.8 on 2025-12-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sells', '0013_warehouse_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='lilis',
            field=models.BooleanField(default=False, verbose_name='Lilis'),
        ),
    ]
